### ISSUE TITLE
Maybe a readme could help

### ISSUE THREAD

**Issue by arzafran** [eukaryote31/electrum-iota#2]
## Two cents from a non python developer

I'm a Frontend developer, but wanted to know a python and was looking for these kind of projects to learn, I'm eager to help but I don't even know how to set up my local environment to start working with python.
I know it's not fully related to your specific project but maybe if you shared some simple commands to set it up and start contributing this app could grow faster.

**Comment by yet-another-account** [comment]
Done :)

Thanks for the suggestion
